Add support for point layers [work in progress]
perliedman/leaflet-multi-style pull request #3
Opened 2017-05-17 14:35 UTC by tomchadwin

#2

Not ready to merge yet.

This works, but in addition to the multiple `L.circleMarker`s, and default marker is produced as well. Any idea why?

2017-05-17 15:02 UTC, tomchadwin commented
Oh, I see. To work around, I have to reimplement `pointToLayer` to retun `null`. Commit coming.

2017-05-17 15:06 UTC, tomchadwin commented
OK, I think this is working now. Can you take a look, @perliedman?

2017-05-17 22:38 UTC, tomchadwin commented
Apologies - error fixed. Ready for review now (I hope).

2017-05-18 06:44 UTC, perliedman requested changes
Nice! This looks ready to merge, but I would also ask you to just add something short to the README to document this.

2017-05-18 07:01 UTC, tomchadwin commented
Of course. I'll add it today.

2017-05-18 08:33 UTC, perliedman approved these changes
Perfect! 👍

2017-05-18 08:33 UTC, merged

2017-05-18 08:36 UTC, perliedman commented
Published this on npm as 1.1.0 if you use that!

2017-05-18 08:47 UTC, tomchadwin commented
Brilliant. And I've integrated it here, if you are interested: https://github.com/tomchadwin/qgis2web/commit/d6494b1139a18b584ce1945e2c7eda52bb1973cb.

Thanks again!